# Rust 错误处理新手教程

Rust 的错误处理与其他语言有所不同。在Java、JS、Python等语言中，你通常是“抛出”异常并“返回 ”成功的值。在Rust中，返回的是一个 `Result`。

`Result<T, E>` 类型是个 [枚举](https://doc.rust-lang.org/book/ch06-01-defining-an-enum.html)，有两个值：`Ok(T)` 表示成功，`Err(E)` 表示失败：

```rust
enum Result<T, E> {
   Ok(T),
   Err(E),
}
```

返回而不是抛出错误是错误处理的一个范式转变。如果你是 Rust 的新手，你可能会不太适应，因为它要求你用（与其他语言）不同的方式来标记错误的原因。

在这篇文章中，我将介绍一些常见的错误处理模式，这样你就会逐渐熟悉 Rust 中的操作方式。

- 忽略错误
- 终止程序
- 使用 fallback  值
- 层层传递错误
- 层层传递多个错误
- 匹配封装的错误
- 库 vs 应用程序
- 创建自定义错误
- 层层传递自定义错误
- 匹配自定义错误

## 忽略错误

让我们从最简单的场景开始 —— 忽略错误。这种处理听起来很粗心，但下面的场景确实会用到：

- 我们正在对代码进行原型设计，不想在错误处理上浪费时间。
- 我们坚信不会发生错误。

比方说，我们正在读取一个非常确定会存在的文件。

```rust
use std::fs;

fn main() {
  let content = fs::read_to_string("./Cargo.toml").unwrap();
  println!("{}", content)
}
```

尽管我们知道该文件存在，但编译器没有办法知道。所以我们使用 `unwrap` 来告诉编译器相信我们并返回里面的值。如果 `read_to_string` 函数返回一个 `Ok()` 值，`unwrap  ` 将得到 `Ok` 的内容并将其赋给 `content` 变量。如果它返回一个错误，将会 “panic”。Panic 要么终止程序，要么退出当前线程。

注意 `unwrap` 在相当多的 Rust 例子中被用来跳过错误处理。这主要是为了方便，不应该在真正的代码中使用它。

## 终止程序

有些错误是无法处理或恢复的。在这些情况下，最好是通过终止程序来*快速失败*。

我们使用与上面相同的例子——读取一个我们确信存在的文件。假定文件对这个程序相当重要，没有它就不能正常工作。如果由于某种原因，这个文件不存在，最好是终止这个程序。

我们可以像以前一样使用 `unwrap`，或者使用 `expect`——它与 `unwrap` 相同，但允许我们添加额外的错误信息。

```rust
use std::fs;

fn main() {
  let content = fs::read_to_string("./Cargo.toml").expect("Can't read Cargo.toml");
  println!("{}", content)
}
```

请参阅： [`panic!`](https://doc.rust-lang.org/std/macro.panic.html)

## 使用 fallback  值

在某些场景中，你可以通过把错误回退到某个默认值来进行处理。

例如，我们正在写一个服务，它监听的端口可以通过环境变量来配置。如果环境变量没有配置，当访问这个值时会出现错误。但我们可以通过回退到某个默认值来很轻松地处理它。

```rust
use std::env;

fn main() {
  let port = env::var("PORT").unwrap_or("3000".to_string());
  println!("{}", port);
}
```

这里我们使用了 `unwrap` 的变体 `unwrap_or`，可以自定义一个默认的值。

请参阅：[`unwrap_or_else`](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap_or_else), [`unwrap_or_default`](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap_or_default)

## 层层传递错误

当你没有足够的上下文来处理错误时，可以把错误层层传递（bubble up or propagate）到调用方。

下面是构造的一个例子，请求一个 webservice 来过去当前的年份：

```rust
use std::collections::HashMap;

fn main() {
  match get_current_date() {
    Ok(date) => println!("We've time travelled to {}!!", date),
    Err(e) => eprintln!("Oh noes, we don't know which era we're in! :( \n  {}", e),
  }
}

fn get_current_date() -> Result<String, reqwest::Error> {
  let url = "https://postman-echo.com/time/object";
  let result = reqwest::blocking::get(url);

  let response = match result {
    Ok(res) => res,
    Err(err) => return Err(err),
  };

  let body = response.json::<HashMap<String, i32>>();

  let json = match body {
    Ok(json) => json,
    Err(err) => return Err(err),
  };

  let date = json["years"].to_string();

  Ok(date)
}
```

`get_current_date` 函数中有两次返回 `Result` 值的函数调用（`get` 和 `json`）。由于 `get_current_date` 中没有足够的上下文来处理错误，因此使用模式匹配把错误传递给 `main`。

使用模式匹配来处理多个或嵌套的错误可能会使代码变得复杂。所以，我们可以用  [`?` 操作符](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-the--operator) 重写上面代码：

```rust
use std::collections::HashMap;

fn main() {
  match get_current_date() {
    Ok(date) => println!("We've time travelled to {}!!", date),
    Err(e) => eprintln!("Oh noes, we don't know which era we're in! :( \n  {}", e),
  }
}

fn get_current_date() -> Result<String, reqwest::Error> {
  let url = "https://postman-echo.com/time/object";
  let res = reqwest::blocking::get(url)?.json::<HashMap<String, i32>>()?;
  let date = res["years"].to_string();

  Ok(date)
}
```

这样看起来简洁多了！

`?` 操作符跟 `unwarp` 很相似，但它会把错误传递给调用方，而不是 panic。请牢记一点，`?` 操作符只能用于返回 `Result` 或 `Option` 类型的函数。

## 层层传递多个错误

在前面的例子中，`get` 和 `json` 函数返回一个 `reqwest::Error` 错误，我们已经用`?`操作符将其传递了。但如果函数返回一个其他的错误值呢？

让我们扩展前面的例子，返回一个格式化的日期而不是年份。

```diff
+ use chrono::NaiveDate;
  use std::collections::HashMap;

  fn main() {
    match get_current_date() {
      Ok(date) => println!("We've time travelled to {}!!", date),
      Err(e) => eprintln!("Oh noes, we don't know which era we're in! :( \n  {}", e),
    }
  }

  fn get_current_date() -> Result<String, reqwest::Error> {
    let url = "https://postman-echo.com/time/object";
    let res = reqwest::blocking::get(url)?.json::<HashMap<String, i32>>()?;
-   let date = res["years"].to_string();
+   let formatted_date = format!("{}-{}-{}", res["years"], res["months"] + 1, res["date"]);
+   let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), "%Y-%m-%d")?;
+   let date = parsed_date.format("%Y %B %d").to_string();

    Ok(date)
  }
```

上面的代码会编译失败，因为 `parse_from_str` 返回一个 `chrono::format::ParseError` 错误而不是 `reqwest::Error`。

我们可以通过用 `Box` 封装错误来解决这个问题。

```diff
  use chrono::NaiveDate;
  use std::collections::HashMap;

  fn main() {
    match get_current_date() {
      Ok(date) => println!("We've time travelled to {}!!", date),
      Err(e) => eprintln!("Oh noes, we don't know which era we're in! :( \n  {}", e),
    }
  }

- fn get_current_date() -> Result<String, reqwest::Error> {
+ fn get_current_date() -> Result<String, Box<dyn std::error::Error>> {
    let url = "https://postman-echo.com/time/object";
    let res = reqwest::blocking::get(url)?.json::<HashMap<String, i32>>()?;

    let formatted_date = format!("{}-{}-{}", res["years"], res["months"] + 1, res["date"]);
    let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), "%Y-%m-%d")?;
    let date = parsed_date.format("%Y %B %d").to_string();

    Ok(date)
  }
```

当我们想返回多个错误时，返回一个特征对象 `Box<dyn std::error::Error>` 是非常方便的!

请参阅： [`anyhow`](https://github.com/dtolnay/anyhow), [`eyre`](https://github.com/yaahc/eyre)

## 匹配封装的错误

到目前为止，我们只在 `main` 函数中打印了错误，但没有处理它们。如果我们想处理和恢复封装的错误，我们需要对它们进行 ”解构“。

```diff
  use chrono::NaiveDate;
  use std::collections::HashMap;

  fn main() {
    match get_current_date() {
      Ok(date) => println!("We've time travelled to {}!!", date),
-     Err(e) => eprintln!("Oh noes, we don't know which era we're in! :( \n  {}", e),
+     Err(e) => {
+       eprintln!("Oh noes, we don't know which era we're in! :(");
+       if let Some(err) = e.downcast_ref::<reqwest::Error>() {
+         eprintln!("Request Error: {}", err)
+       } else if let Some(err) = e.downcast_ref::<chrono::format::ParseError>() {
+         eprintln!("Parse Error: {}", err)
+       }
+     }
    }
  }

  fn get_current_date() -> Result<String, Box<dyn std::error::Error>> {
    let url = "https://postman-echo.com/time/object";
    let res = reqwest::blocking::get(url)?.json::<HashMap<String, i32>>()?;

    let formatted_date = format!("{}-{}-{}", res["years"], res["months"] + 1, res["date"]);
    let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), "%Y-%m-%d")?;
    let date = parsed_date.format("%Y %B %d").to_string();

    Ok(date)
  }
```

请注意，我们需要了解 `get_current_date` 的实现细节（里面不同的错误），以便能够在 `main` 中进行解构。

请参阅：[`downcast`](https://doc.rust-lang.org/std/error/trait.Error.html#method.downcast), [`downcast_mut`](https://doc.rust-lang.org/std/error/trait.Error.html#method.downcast_mut)

## 库 vs 应用程序

如前所述，封装错误的缺点是，如果我们想处理底层错误，我们需要了解实现细节。当我们返回  `Box<dyn std::error::Error>` 时，具体的类型信息被抹去了。为了以不同的方式处理不同的错误，我们需要将它们解构到具体的类型中，这种转换在运行时可能会失败。

然而，在没有上下文的情况下，说某个东西是 ”短板“ 没有什么说服力。一个很好的标准就是根据你所写的代码是一个 ”应用程序“ 还是一个 ”库“。

### 应用程序

- 你写的代码会被终端用户使用。
- 由应用程序代码产生的大多数错误不会被处理，而是被记录或报告给用户。
- 使用封装的错误没有什么大问题。

### 库

- 你所写的代码会被其他代码消费。一个”库“可能是开源 crate、内部库等。
- 错误是你的库 API 的一部分,所以你的消费方知道应该 expect 哪些错误已经如何恢复。
- 你的消费方经常处理你的库的错误，所以它们需要结构化，并易于对其进行 [穷举匹配](https://doc.rust-lang.org/1.30.0/book/2018-edition/ch06-02-match.html#matches-are-exhaustive)。
- 如果你返回封装的错误，那么你的消费方就需要注意你的代码、你的依赖关系等所产生的错误
- 我们可以返回自定义错误，而不是封装的错误

## 创建自定义错误

对于库代码，我们可以将所有的错误转换为自定义错误并传递它们，而不是封装的错误。在我们的例子中，目前有两个错误—— `reqwest::Error ` 和 `chrono::format::ParseError`。我们可以将它们分别转换为 `MyCustomError::HttpError` 和 `MyCustomError::ParseError`。

让我们开始创建一个枚举来保存我们的两个错误变量。

```rust
// error.rs

pub enum MyCustomError {
  HttpError,
  ParseError,
}
```

[`Error`](https://doc.rust-lang.org/std/error/trait.Error.html) 特性要求我们实现 [`Debug`](https://doc.rust-lang.org/std/fmt/trait.Debug.html) 和 [`Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html) 特性。

```rust
// error.rs

use std::fmt;

#[derive(Debug)]
pub enum MyCustomError {
  HttpError,
  ParseError,
}

impl std::error::Error for MyCustomError {}

impl fmt::Display for MyCustomError {
  fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
    match self {
      MyCustomError::HttpError => write!(f, "HTTP Error"),
      MyCustomError::ParseError => write!(f, "Parse Error"),
    }
  }
}
```

我们已经创建了我们自己的自定义错误!

这显然是一个简单的例子，因为错误变量并不包含太多的错误信息。但这应该足以作为创建更复杂、更真实的自定义错误的起点。下面是一些现实生活中的例子。[ripgrep](https://github.com/BurntSushi/ripgrep/blob/12.1.1/crates/regex/src/error.rs), [reqwest](https://github.com/seanmonstar/reqwest/blob/v0.10.7/src/error.rs), [csv](https://github.com/BurntSushi/rust-csv/blob/master/src/error.rs) 和 [serde_json](https://github.com/serde-rs/json/blob/master/src/error.rs)

请参阅： [`thiserror`](https://github.com/dtolnay/thiserror), [`snafu`](https://github.com/shepmaster/snafu)

## 层层传递自定义错误

我们来更新下代码，返回刚刚创建的自定义错误：

```diff
  // main.rs

+ mod error;

  use chrono::NaiveDate;
+ use error::MyCustomError;
  use std::collections::HashMap;

  fn main() {
    // skipped, will get back later
  }

- fn get_current_date() -> Result<String, Box<dyn std::error::Error>> {
+ fn get_current_date() -> Result<String, MyCustomError> {
    let url = "https://postman-echo.com/time/object";
-   let res = reqwest::blocking::get(url)?.json::<HashMap<String, i32>>()?;
+   let res = reqwest::blocking::get(url)
+     .map_err(|_| MyCustomError::HttpError)?
+     .json::<HashMap<String, i32>>()
+     .map_err(|_| MyCustomError::HttpError)?;

    let formatted_date = format!("{}-{}-{}", res["years"], res["months"] + 1, res["date"]);
-   let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), "%Y-%m-%d")?;
+   let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), "%Y-%m-%d")
+     .map_err(|_| MyCustomError::ParseError)?;
    let date = parsed_date.format("%Y %B %d").to_string();

    Ok(date)
  }
```

注意我们是如何使用 `map_err` 将错误从一种类型转换为另一种类型的。

但事情代码变得冗长了——我们的函数中充满了这些 `map_err` 的调用。当使用 `?` 操作符的时候，我们可以实现 [`From`](https://doc.rust-lang.org/std/convert/trait.From.html) 特性来自动强行获取错误的类型。

```diff
  // error.rs

  use std::fmt;

  #[derive(Debug)]
  pub enum MyCustomError {
    HttpError,
    ParseError,
  }

  impl std::error::Error for MyCustomError {}

  impl fmt::Display for MyCustomError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
      match self {
        MyCustomError::HttpError => write!(f, "HTTP Error"),
        MyCustomError::ParseError => write!(f, "Parse Error"),
      }
    }
  }

+ impl From<reqwest::Error> for MyCustomError {
+   fn from(_: reqwest::Error) -> Self {
+     MyCustomError::HttpError
+   }
+ }

+ impl From<chrono::format::ParseError> for MyCustomError {
+   fn from(_: chrono::format::ParseError) -> Self {
+     MyCustomError::ParseError
+   }
+ }
  // main.rs

  mod error;

  use chrono::NaiveDate;
  use error::MyCustomError;
  use std::collections::HashMap;

  fn main() {
    // skipped, will get back later
  }

  fn get_current_date() -> Result<String, MyCustomError> {
    let url = "https://postman-echo.com/time/object";
-   let res = reqwest::blocking::get(url)
-     .map_err(|_| MyCustomError::HttpError)?
-     .json::<HashMap<String, i32>>()
-     .map_err(|_| MyCustomError::HttpError)?;
+   let res = reqwest::blocking::get(url)?.json::<HashMap<String, i32>>()?;

    let formatted_date = format!("{}-{}-{}", res["years"], res["months"] + 1, res["date"]);
-   let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), "%Y-%m-%d")
-     .map_err(|_| MyCustomError::ParseError)?;
+   let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), "%Y-%m-%d")?;
    let date = parsed_date.format("%Y %B %d").to_string();

    Ok(date)
  }
```

我们已经删除了 `map_err`，代码看起来干净多了

然而，`From` 特性并不神奇，有些时候我们需要使用 `map_err`。在上面的例子中，我们把类型转换从  `get_current_date` 函数里面移到了 `From<X> for MyCustomError` 实现里面。当从一个错误转换到 `MyCustomError` 所需的信息可以从原始错误对象中获得时，这个方法很有效。如果不是，我们需要在 `get_current_date` 里面使用 `map_err`。

## 匹配自定义错误

我们一直忽略了在 `main` 中的修改，我们可以这样处理自定义错误：

```diff
  // main.rs

  mod error;

  use chrono::NaiveDate;
  use error::MyCustomError;
  use std::collections::HashMap;

  fn main() {
    match get_current_date() {
      Ok(date) => println!("We've time travelled to {}!!", date),
      Err(e) => {
        eprintln!("Oh noes, we don't know which era we're in! :(");
-       if let Some(err) = e.downcast_ref::<reqwest::Error>() {
-         eprintln!("Request Error: {}", err)
-       } else if let Some(err) = e.downcast_ref::<chrono::format::ParseError>() {
-         eprintln!("Parse Error: {}", err)
-       }
+       match e {
+         MyCustomError::HttpError => eprintln!("Request Error: {}", e),
+         MyCustomError::ParseError => eprintln!("Parse Error: {}", e),
+       }
      }
    }
  }

  fn get_current_date() -> Result<String, MyCustomError> {
    let url = "https://postman-echo.com/time/object";
    let res = reqwest::blocking::get(url)?.json::<HashMap<String, i32>>()?;

    let formatted_date = format!("{}-{}-{}", res["years"], res["months"] + 1, res["date"]);
    let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), "%Y-%m-%d")?;
    let date = parsed_date.format("%Y %B %d").to_string();

    Ok(date)
  }
```

请注意它与封装的错误的不同，我们实际上可以匹配 `MyCustomError` 枚举的变量。

## 总结

感谢阅读！ 我希望这篇文章对介绍 Rust 中错误处理的基础知识有所帮助。我已经把这些例子添加到了[GitHub中的repo](https://github.com/sheshbabu/rust-error-handling-examples)，你可以用它来练习。如果你有更多问题，请通过 sheshbabu [at] gmail.com 联系我。欢迎在 [Twitter](https://twitter.com/sheshbabu) 上关注我，以获得更多类似的文章 :)